# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Reu2WDrazb4d9NEE6Ume94xN3lW9SK5l
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from gtts import gTTS
# import os
# 
# # App settings
# st.set_page_config(page_title="EchoVerse – Free Audiobook Creator", layout="centered")
# 
# st.title("📚 EchoVerse – Free AI Audiobook Tool")
# st.write("✨ 100% Free using **gTTS** (Google Text-to-Speech) – no API key required!")
# 
# # Upload text file
# uploaded_file = st.file_uploader("📂 Upload a .txt file", type=["txt"])
# 
# # Or paste text directly
# input_text = st.text_area("✍️ Or paste your text here:")
# 
# # Language selector
# lang = st.selectbox(
#     "🌎 Choose language:",
#     ["en", "hi", "fr", "es", "de", "it", "pt", "ru", "ja", "zh-cn"]
# )
# 
# # Generate audiobook
# if st.button("🎧 Create Audiobook"):
#     if uploaded_file is not None:
#         text = uploaded_file.read().decode("utf-8")
#     else:
#         text = input_text
# 
#     if text.strip() == "":
#         st.warning("⚠️ Please provide some text to convert.")
#     else:
#         # Generate speech
#         tts = gTTS(text=text, lang=lang)
#         filename = "audiobook.mp3"
#         tts.save(filename)
# 
#         # Play + download
#         st.audio(filename)
#         st.success("✅ Audiobook generated successfully!")
#         with open(filename, "rb") as f:
#             st.download_button("⬇️ Download Audiobook", f, file_name="audiobook.mp3")
#

from pyngrok import ngrok

# Set ngrok authtoken (do this once per runtime)
ngrok.set_auth_token("31xniORkZTRVih2G1aMVuU0G4jW_85m1qHKdaTAk1fZ4RdPZx")

public_url = ngrok.connect(8501)
print("🚀 EchoVerse is live at:", public_url)
